package:
  name: pyani
  version: "0.2.3"

source:
  fn: pyani-0.2.3.tar.gz
  url: https://pypi.python.org/packages/02/90/2a97a12577c270458e66580e1cc9b9d347193cdce07848678242013d32e3/pyani-0.2.3.tar.gz
  md5: 98b16a167999061e649cef483d1ba6a9

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - biopython
    - matplotlib
    - pandas
    - scipy
    - seaborn

  run:
    - python
    - biopython
    - matplotlib
    - pandas
    - scipy
    - seaborn

test:
  imports:
    - pyani

  commands:
    - average_nucleotide_identity.py --help
    - genbank_get_genomes_by_taxon.py --help
    - cd tests && nosetests

  requires:
    - nose

about:
  home: http://widdowquinn.github.io/pyani/
  license: MIT License
  summary: 'pyani provides a package and script for calculation of genome-scale average nucleotide identity.'
  license_family: MIT
